"""new fields in user model 

Revision ID: 46be3d39fd2b
Revises: 618c9cce325f
Create Date: 2018-07-04 17:12:42.163134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46be3d39fd2b'
down_revision = '618c9cce325f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
